#!/bin/bash

importMenus(){
    cp ../../5Menu/Files/allMenus ../Files
    }

checkTaxBash(){
    cd ../TaxBash
    rm -i *~
    cd ../Main
    }

createTaxBash(){
    rm ../Files/tax-bash
    echo "../Files/tax-bash has been removed."    
    ../Make/makeTaxBash.sh
    echo "../Files/tax-bash has been created."
    cat ../Files/allMenus >> ../Files/tax-bash
    echo "../Files/allMenus have been added to tax-bash"
    cat ../Files/startMenu2 >> ../Files/tax-bash
    echo "../Files/setMenu2 added to tax-bash"
    chmod 755 ../Files/tax-bash
    echo "Permissions on tax-bash set to 755."
    sleep 3
} 

exportTax-bash(){
    cp ../Files/tax-bash ../../7App/Main/tax-bash
    cp ../Files/tax-bash ../../T21/Main/tax-bash
    }


set_menu_choices() {
while true;
  do     
  clear
  echo
  echo "This menu is for Developers writing the UI file tax-bash."
  echo
  echo "   1)  import allMenus"
  echo "   2)  remove any backup(~) files from ../TaxBash"
  echo "   3)  create tax-bash"
  echo "   4)  export tax-bash"
  echo 
  echo "   q) Quit"
 
  echo "Please enter the number or letter(s) of your choice then press return."
  read menu_choice

  case "$menu_choice" in
      
      1)  importMenus;;
      2)  checkTaxBash;;
      3)  createTaxBash;;
      4)  exportTax-bash;;
      q)  exit;;
      *)  echo "Sorry, choice not recognized."
    esac
  done  
}




while true;
do
    set_menu_choices	
done
    
#Tidy up and leave

echo "Finished"

exit 0

