#!/bin/bash

#Copyright(C) 2023, 2024 Phillips Wedemeyer
#
#This file is part of a program called Tax-bash.
#
#Tax-bash is free software: you can redistibute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#Tax-bash is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with Tax-bash.  If not, see <https://www.gnu.org/licenses/>.
#
#





viewReadMe(){
cat README | less
return
}




viewReadMe(){
cat ../README | less
return
}



choice00NotAllowed(){
	echo "Choice $1 is not allowed."
	sleep 5
}



importLastYrReturn(){
echo "Importing last year's return."
sleep 1

if [ -f ../../T16/Xml/taxlogic.final ]
then
cp ../../T16/Xml/taxlogic.final ../Xml/taxlogic.PrevYear
else
echo "../../T16/Xml/taxlogic.final is not a regular file."
echo "      Will use taxlogic.frame instead."
cp ../Xml/taxlogic.frame ../Xml/taxlogic.PrevYear
fi
return
}


importLastYrData(){

if [ -d ../../T16/Data/ ]
then
echo "Last years Data directory exists"
echo "The program will import any data files"
echo "in that directory."


cp ../../T16/Data/*_data.xml ../Data


for file in ../Data/Background*_data.xml
do
    echo "Processing $file"
    
sed 's/<instructions\/>/<instructions><\/instructions>/;s/<text\/>/<text><\/text>/;s/<number\/>/<number><\/number>/;s/<override\/>/<override><\/override>/;s/<item\/>/<item><\/item>/' ../Data/$file  >  ../Data/$file.tmp

sed '/<number>/d' ../Data/$file.tmp  >  ../Data/$file.tmp2
sed '/<number\/>/d' ../Data/$file.tmp2 > ../Data/$file.tmp3

sed '/<override>/i\
<number><\/number>
<goesTo>
</goesTo>
<comesFrom>
</comesFrom>' ../Data/$file.tmp3  >  ../Data/$file.tmp4


sed 's/<instructions\/>/<instructions><\/instructions>/;s/<text\/>/<text><\/text>/;s/<number\/>/<number><\/number>/;s/<override\/>/<override><\/override>/;s/<item\/>//' ../Data/$file.tmp5  >  ../Data/$file.tmp6

sed 's/^$/d' ../Data/$file.tmp6 ../Data/$file.temp

mv ../Data/$file.temp ../Data/$file

done



 

rm ../Data/*.tmp
rm ../Data/*.tmp2
rm ../Data/*.tmp3
rm ../Data/*.tmp4
rm ../Data/*.tmp5
echo



echo "Last years data files have now been verified for their format."
sleep 2


else
echo "Last year's Data directory doesn't exist"
echo "This year's empty data files are now ready to use."
fi

return
}



importGnuCash(){




for file in $(dir -ra $GNUCASHFILES/*.gnucash)
do

foo=$file

newname=${foo#~/*.2}

newername='2'$newname

cp $foo ../GnuCash/$newername.gz
gunzip ../GnuCash/$newername.gz

rm ../GnuCash/*.current
cp ../GnuCash/$newername ../GnuCash/$newername.current
dir ../GnuCash

break;

done

}




refreshAll() {


echo "Your data is being refreshed. This will take about 50 seconds."
echo "Please wait for the program to return." 


java $XALANJAVAJAR org.apache.xalan.xslt.Process -in ../GnuCash/*.current -xsl ../BaseXsl/year.xsl -out ../BaseData/year.xml

java $XALANJAVAJAR org.apache.xalan.xslt.Process -in ../BaseData/year.xml -xsl ../BaseXsl/splita.xsl -out ../BaseData/split.xml

java $XALANJAVAJAR org.apache.xalan.xslt.Process -in ../BaseData/split.xml -xsl ../BaseXsl/dollarvalue.xsl -out ../BaseData/dollarvalue.xml



java $XALANJAVAJAR org.apache.xalan.xslt.Process -in ../BaseData/dollarvalue.xml -xsl ../BaseXsl/accounts.xsl -out ../Accounts.init/accounts.xml

cp -r ../Accounts.init/* ../Accounts




cp -r ../Accounts.edited/* ../Accounts


rm ../BaseData/dollarvalue.xml


java $XALANJAVAJAR org.apache.xalan.xslt.Process -in ../Accounts/accounts.xml -xsl ../BaseXsl/rejoin.xsl -out ../BaseData/dollarvalue.xml


java $XALANJAVAJAR org.apache.xalan.xslt.Process -in ../BaseData/dollarvalue.xml -xsl ../BaseXsl/totl.xsl -out ../BaseData/totl.xml

return 
}



refreshTl() {


	

echo "Your data is being refreshed. This will take about 30 seconds."
echo "Please wait for the program to return." 


sed 's/<\/IRSForms>/include(\.\.\/Xml\/all.xml)<\/IRSForms>/' ../BaseData/totl.xml > ../BaseData/sedtotl.xml

rm ../Xml/all.xml

cat ../Data/*.xml >> ../Xml/all.xml

m4 ../BaseData/sedtotl.xml > ../Total/totlall.xml

java $XALANJAVAJAR org.apache.xalan.xslt.Process -in ../Total/totlall.xml -xsl ../BaseXsl/taxlines.xsl -out ../Taxlines/linesall.xml


java $XALANJAVAJAR org.apache.xalan.xslt.Process -in ../Taxlines/linesall.xml  -xsl ../Xsl/taxlogic.xsl -out ../Output/all.xml

sed 's/-Copy/_Copy/' ../Output/all.xml > ../Output/all.tmp
cp ../Output/all.tmp ../Output/all.xml
rm ../Output/all.tmp

java $XALANJAVAJAR org.apache.xalan.xslt.Process -in ../Output/all.xml -xsl ../BaseXsl/makeOutputFiles.xsl -out ../Out/outputforms.xml

return 
}




showValue(){
sed -n '/<$1>/s/>$3>//;s/<\/$3//p' $1 $2
}    



listAccountsPlus() {

java $XALANJAVAJAR org.apache.xalan.xslt.Process -in ../Work/totl.xml -xsl ../Xsl/listAccounts.xsl -out ../Work/listAccounts.xml

sed 's/<?xml version="1.0".*?>//;s/<Accounts.*gnc">//;s/<account>//g;s/<\/account>/\n/g;s/<\/Accounts>//' ../Work/listAccounts.xml > ../Work/listAccounts.xml.tmp

cat ../Work/listAccounts.xml.tmp


for account in $(cat ../Work/listAccounts.xml.tmp)
do
    echo $account > ../Work/listAccounts.xml.temp
        
done

firefox -new-tab ../Work/listAccounts.xml.tmp > /dev/null 2>&1 &
return
}




listAccounts() {

java $XALANJAVAJAR org.apache.xalan.xslt.Process -in ../Work/totl.xml -xsl ../Xsl/listAccounts.xsl -out ../Work/listAccounts.xml


firefox -new-tab ../Work/listAccounts.xml > /dev/null 2>&1 &
return
}



showAccounts(){
clear
echo "In order to show the accounts associated with a particular"
echo "Form or Schedule you need to specify the form or schedule you desire."
echo "The name of the form is case sensitive and has no spaces."
echo "The possibilities are:"
echo "SchedA"
echo "SchedB"
echo "SchedC"
echo "SchedH"
echo "1040"
echo "8829"


echo "For which form or schedule would you like to see the accounts and their transactions? Enter a form or schedule from the list above."
read formSch

java $XALANJAVAJAR org.apache.xalan.xslt.Process -in ../Work/taxlines.xml -xsl ../Xsl/oneForm.xsl -PARAM form $formSch -out ../Work/oneForm.xml 

java $XALANJAVAJAR org.apache.xalan.xslt.Process -in ../Work/oneForm.xml -xsl ../2Fo/trnsPerTaxline.2fo -out ../Work/trnsPerForm.fo

java $FOPJAVAJAR org.apache.fop.cli.Main ../Work/trnsPerForm.fo ../Pdf/trnsPerForm.pdf

qpdfview  --unique ../Pdf/trnsPerForm.pdf > /dev/null 2>&1 &

return
}




oneAcct() {
list=""
echo
echo "This function will list the transactions for one account." 
echo "You will need to supply the name of the one account you want to see."
echo
echo "Do you need to see a list of all available accounts?"
echo "Enter y or n."
read list

if [ "$list" = "y" ]
  then
    java $XALANJAVAJAR org.apache.xalan.xslt.Process -in ../BaseData/totl.xml -xsl ../BaseXsl/listAccounts.xsl -out ../BaseData/listAccounts.xml

firefox -new-tab ../BaseData/listAccounts.xml > /dev/null 2>&1 &
fi

echo
echo "Type the name of the account you want to see:"
read account
echo
echo "The transactions will be sorted by date-posted."
echo "Would you prefer the transactions be sorted by description? If so enter 'yes'."
read description

if [ "$description" = "yes" ]
  then
echo "description = "yes"."
java $XALANJAVAJAR org.apache.xalan.xslt.Process -in ../BaseData/totl.xml -xsl ../BaseXsl/oneAcctDesc.xsl -out ../BaseData/oneAcct.xml -PARAM AName $account
 else
java $XALANJAVAJAR org.apache.xalan.xslt.Process -in ../BaseData/totl.xml  -xsl ../BaseXsl/oneAcctDate.xsl -out ../BaseData/oneAcct.xml -PARAM AName $account
fi

java $XALANJAVAJAR org.apache.xalan.xslt.Process -in ../BaseData/oneAcct.xml -xsl ../Base2Fo/trnsPerAcct4.2fo -out ../Fo/oneAcct.fo

fop ../Fo/oneAcct.fo ../Pdf/oneAcct.pdf

qpdfview --unique ../Pdf/oneAcct.pdf > /dev/null 2>&1 &

}




edit_account(){

list=""
echo
echo "This function will edit the transactions for one account." 
echo "You will need to supply the name of the one account you want to edit."
echo
echo "Do you need to see a list of all available accounts?"
echo "Enter y or n."
read list

if [ "$list" = "y" ]
  then
    echo $list

    java $XALANJAVAJAR org.apache.xalan.xslt.Process -in ../Work/totl.xml -xsl ../Xsl/listAccounts.xsl -out ../Work/listAccounts.xml

firefox ../Work/listAccounts.xml > /dev/null 2>&1 &
 #   qpdfview --unique ../Work/listAccounts.xml > /dev/null 2>&1 &
fi

echo
echo Type the name of the account you want to edit:
read account

if [ -e ../Accounts.edited/$account.xml ]; then
    emacs ../Accounts.edited/$account.xml
else
    cp ../Accounts/$account.xml ../Accounts.edited/$account.xml
    emacs ../Accounts.edited/$account.xml
fi



return
}




yOrn(){
response=$1
while [ "$response" != "y" ]
do
case "$response" in
    y) return 0
       ;;
    n) return 1
       ;;
    *) echo "Response not recognized. Please enter y or n."
       read response
       ;;
esac
done    
}


showForm2() {

for file in ../2Fo/$1_Copy$2*.2fo
do
    file1=${file#../2Fo/}
   file2=${file1%2fo}
    file2+="fo"
    java $XALANJAVAJAR org.apache.xalan.xslt.Process -in ../Output/$1_Copy$2.xml -xsl ../2Fo/$file1 -out ../Fo/$file2
    file3=${file1%2fo}
    file3+="pdf"
    fop ../Fo/$file2 ../Pdf/$file3
done

qpdfview --unique ../Pdf/$1_Copy$2.pdf >/dev/null 2>&1 &

return
}



showFormLocal() {

params=$#
echo "$params"
if [ $params = "3" ]; then
    infile="../Data/$1_Copy$2_$3_*.xml"
    tempfile="../Data/$1_Copy$2_$3_*.tmp"
elif [ $params = "4" ]; then
    infile="../Data/$1_Copy$2_$3_*.xml"
    tempfile="../Data/$1_Copy$2_$3_*.tmp"
fi
echo "infile is $infile. tempfile=$tempfile."

sed '/<bgcolor>/s/^.*$/<bgcolor>yellow<\/bgcolor>/' $infile > $tempfile
mv $tempfile $infile

showForm $1 $2


sed '/<bgcolor>/s/^.*$/<bgcolor><\/bgcolor>/' $infile > $tempfile
mv $tempfile $infile

return
}




editDInstructions(){
    echo "Editing instructions is only for development."
    echo "This ability will be removed from the working program."

    infile="../Data/$1_$2_$3_*.xml"
    tempfile="../Data/$1_$2_$3_*.tmp"

echo "The local instructions for this line are:"
java $XALANJAVAJAR org.apache.xalan.xslt.Process -in $infile -xsl ../BaseXsl/instout.xsl

echo "Do you wish to enter or change the local instructions for this line?"
echo "Enter y or n."
read this

if yOrn $this
then
       echo "Editing instructions is not currently possible."
       echo "Please enter any instructions you wish to give:"
       read instructions
       java $XALANJAVAJAR org.apache.xalan.xslt.Process -in $infile -xsl ../BaseXsl/instDin.xsl -PARAM instructions "$instructions" -out $tempfile
	mv $tempfile $infile
	cat $infile
else
	echo "The instructions have been kept unchanged."
fi

echo "The local instructions for this line are:"
java $XALANJAVAJAR org.apache.xalan.xslt.Process -in $infile -xsl ../BaseXsl/instout.xsl

}    


editTInstructions(){
    echo "Editing instructions is only for development."
    echo "This ability will be removed from the working program."

    infile="../Data/$1_$2_$3_*.xml"
    tempfile="../Data/$1_$2_$3_*.tmp"

echo "The local instructions for this line are:"
java $XALANJAVAJAR org.apache.xalan.xslt.Process -in $infile -xsl ../BaseXsl/instout.xsl
echo "Do you wish to enter or change the local instructions for this line?"
echo "Enter y or n."
read this

if yOrn $this
then
       echo "Editing existing instructions is not currently possible."
       echo "Please enter anew any instructions you wish to give:"
       read instructions
       java $XALANJAVAJAR org.apache.xalan.xslt.Process -in $infile -xsl ../BaseXsl/instTin.xsl -PARAM instructions "$instructions" -out $tempfile
       mv $tempfile $infile
       cat $infile
else
	echo "The instructions have been kept unchanged."
fi

echo "The local instructions for this line are:"
java $XALANJAVAJAR org.apache.xalan.xslt.Process -in $infile -xsl ../BaseXsl/instout.xsl
}    



showInstructions(){
    #The value of this line is shown as <instructions> in the data file:
params=$#
if [ $params = "3" ]; then
    infile="../Data/$1_Copy$2_*.xml"
    tempfile="../Data/$1_Copy$2_*.tmp"
elif [ $params = "4" ]; then
    infile="../Data/$1_Copy$2_$3_*.xml"
    tempfile="../Data/$1_Copy$2_$3_*.tmp"
fi
echo "infile is $infile. tempfile=$tempfile."
    
echo "The local instructions for this line are:"
java $XALANJAVAJAR org.apache.xalan.xslt.Process -in $infile -xsl ../BaseXsl/instout.xsl   
echo

return    
}




showIRSinstructions(){
params=$#
echo "$params"
if [ $params = "3" ]; then
    pgNo="$3"
   
elif [ $params = "4" ]; then
    pgNo=$4
    
fi
echo $pgNo    
qpdfview --unique ../IRS/i1040gi.pdf#$pgNo &
return
}



showDataFile(){
clear
params=$#
if [ $params = "3" ]; then
    infile="../Data/$1_Copy$2_$3_*.xml"
    tempfile="../Data/$1_Copy$2_$3_*.tmp"
elif [ $params = "4" ]; then
    infile="../Data/$1_Copy$2_$3_*.xml"
    tempfile="../Data/$1_Copy$2_$3_*.tmp"
fi

sed '/^ *$/d' $infile > $tempfile
mv $tempfile $infile

sed 's/^ *//' $infile > $tempfile
mv $tempfile $infile

sed '/<item><\/item>/d' $infile > $tempfile
mv $tempfile $infile


cat $infile
echo " "
echo "Are you ready to continue?"
echo "If so, press y or n."
read this
if yOrn $this
then
	return
fi
}




edit-numberline(){

params=$#
    infile="../Data/$1_Copy$2_$3_*.xml"
    tempfile="../Data/$1_Copy$2_$3_*.tmp"

echo "This line has a numerical value."
echo "Preferably this value is drawn from your GnuCash data."
echo "This is done by adding up the totals of the accounts you specify here."
echo "This method allows the program to enter the amount automatically in the future."
echo 
echo "If the value to be entered here is not in your GnuCash accounts, or"
echo "if you wish to temporarily override the value of this line,"
echo "you can return to the previous menu and override the value."
echo
echo "The totals of the following accounts are currently"
echo "being added together to produce the value of the line."
java $XALANJAVAJAR org.apache.xalan.xslt.Process -in $infile -xsl ../BaseXsl/acctout.xsl

echo
echo "Do you wish to add an account? Enter y or n."
read choice

while yOrn $choice
do      
       echo "Enter the name of the account you wish to add."
       read add
       java $XALANJAVAJAR org.apache.xalan.xslt.Process -in $infile -xsl ../BaseXsl/acctadd.xsl -out $tempfile -PARAM item "$add"

       mv $tempfile $infile
       echo "The following accounts are now listed:"
       java $XALANJAVAJAR org.apache.xalan.xslt.Process -in $infile -xsl ../BaseXsl/acctout.xsl
       echo "Do you wish to add the name of another account? Enter y or n."
       read choice
done
clear
echo "Do you wish to remove an account? Enter y or n."
read choice2

while yOrn $choice2 
do      
       echo "Enter the name of the account you wish to remove."
       read remove
       java $XALANJAVAJAR org.apache.xalan.xslt.Process -in $infile -xsl ../BaseXsl/acctremove.xsl -PARAM acct "$remove" -out $tempfile
       mv $tempfile $infile
       clear
       echo "The following accounts are now listed:"
       java $XALANJAVAJAR org.apache.xalan.xslt.Process -in $infile -xsl ../BaseXsl/acctout.xsl

       echo "If you wish to remove the name of another account? Enter y or n."
       read choice2
done

echo "The following accounts are now listed:"
       java $XALANJAVAJAR org.apache.xalan.xslt.Process -in $infile -xsl ../BaseXsl/acctout.xsl

echo

echo
echo "Remember that this change will not show up"
echo "until you have refreshed (recalculated) your data."
echo 
echo "Do you wish to refresh your data now?"
echo "Enter y or n"
read this
if yOrn "$this"
   then
       refreshTl $1 $2
   else
       echo "Data has not been refreshed."
fi




return
}



edit_textline(){

    infile="../Data/$1_Copy$2_$3_text.xml"
    tempfile="../Data/$1_Copy$2_$3_text.tmp"
echo "infile is $infile. tempfile=$tempfile."

sed '/^ *$/d' $infile > $tempfile
mv $tempfile $infile

sed 's/^ *//' $infile > $tempfile
mv $tempfile $infile

sed 's/<text\/>/<text><\/text>/' $infile > $tempfile 
mv $tempfile $infile

echo
echo "The value of this line is currently:"
java $XALANJAVAJAR org.apache.xalan.xslt.Process -in $infile -xsl ../BaseXsl/textout.xsl


echo
echo "Do you wish to change the value of this text line?" 
echo "Enter y or n"
read this
if yOrn "$this"
   then
       echo
       echo "To change the text value of this line, please enter the new value now:"
       read text
       java $XALANJAVAJAR org.apache.xalan.xslt.Process -in $infile -xsl ../BaseXsl/textin.xsl -out $tempfile -PARAM text "$text"
       mv $tempfile $infile
       echo
       #Now you are shown the final value of the text line. 
       echo "This text line now reads:"
       java $XALANJAVAJAR org.apache.xalan.xslt.Process -in $infile -xsl ../BaseXsl/textout.xsl
       echo
else
    echo
    echo "The text value has been kept unchanged."
fi    



return
}




edit-override(){

params=$#
    infile="../Data/$1_Copy$2_$3_data.xml"
    tempfile="../Data/$1_Copy$2_$3_data.tmp"

echo "This line has a numerical value."
echo "Preferably this value is drawn from you GnuCash data."
echo "This is done by adding up the totals of the accounts you specify here."
echo "This method allows the program to enter the amount automatically in the future."
echo "To do this you should return to the previous menu and choose (6)."
echo

echo "If the numerical value desired is not in your GnuCash data,"
echo "or you wish to temporarily or permanently override the value"
echo "obtained from the accounts method described above,"
echo "you may enter the desired number as an override here."
 
     "you can procede here."

echo " "

echo
echo "The value of the override is currently:"
java $XALANJAVAJAR org.apache.xalan.xslt.Process -in $infile -xsl ../BaseXsl/overout.xsl

echo
echo "Do you wish to change this override? Enter y or n."
read choice

while yOrn $choice
do
echo "To change the value of the override, enter the new value now:"
read override
java $XALANJAVAJAR org.apache.xalan.xslt.Process -in $infile -xsl ../BaseXsl/overin.xsl -out $tempfile -PARAM override "$override"
mv $tempfile $infile
choice="n"
done

clear
echo "The value of the override is currently:"
java $XALANJAVAJAR org.apache.xalan.xslt.Process -in $infile -xsl ../BaseXsl/overout.xsl

echo
echo "Remember that this change will not show up"
echo "until you have refreshed (recalculated) your data."
echo "Since refreshing your data takes about 30 seconds,"
echo "You may wish to make other changes to your data"
echo "before you recalculate all your data."
echo 
echo "Do you wish to refresh your data now?"
echo "Enter y or n"
read this
if yOrn "$this"
then
       refreshTl $1 $2
else
    echo "Data has not been refreshed."
fi
   

return    
}




comesFrom(){

    infile="../Data/$1_$2_$3_*.xml"
    tempfile="../Data/$1_$2_$3_*.tmp"
echo "infile is $infile tempfile is $tempfile"

echo "This line comes from:"
foo=$(sed -n '/<from>/s/<from>//;s/<\/from>//p' $infile)

echo $foo

for form in $foo
do	    
    echo "Do you want to show $form? Enter y or n."
    read choice
    
    if yOrn $choice
       then
       showFormLocal $form
    fi
done    

return
}    




comes_from2(){
    infile="../Data/$1_$2_$3_*.xml"
    tempfile="../Data/$1_$2_$3_*.tmp"
echo "infile is $infile tempfile is $tempfile"

echo "This line comes from:"
foo=$(sed -n '/<from>/s/<from>//;s/<\/from>//p' $infile)

echo $foo


    select file in $foo;
do
    set_line_menu_text ../Data/$foo.xml
done
}



goesTo(){

    infile="../Data/$1_$2_$3_*.xml"
    tempfile="../Data/$1_$2_$3_*.tmp"


echo "This line goes to:"
foo=$(sed -n '/<to>/s/<to>//;s/<\/to>//p' $infile)
echo $foo

for form in $foo
do	    
    echo "Do you want to show $form? Enter y or n."
    read choice
    
    if yOrn $choice
       then
       showForm $form
    fi
done    

return
}







enterNotes(){

    infile="../Data/$1_$2_$3_*.xml"
    tempfile="../Data/$1_$2_$3_*.tmp"

    echo "Currently, your notes on this line read:"
    java $XALANJAVAJAR org.apache.xalan.xslt.Process -in $infile -xsl ../BaseXsl/notesout.xsl
    echo
    echo
    echo "Do you wish to change these notes"
    echo "or enter new notes to yourself about this line?"
echo "Enter y or n."
read this
if yOrn "$this"
then
       echo "Editing your notes is not currently possible."
       echo "Please enter any notes you wish to make:"
       read note
       java $XALANJAVAJAR org.apache.xalan.xslt.Process -in $infile -xsl ../BaseXsl/notesin.xsl -PARAM notes "$note" -out $tempfile
	mv $tempfile $infile
	echo
	echo "Your notes now read:"
       java $XALANJAVAJAR org.apache.xalan.xslt.Process -in $infile -xsl ../BaseXsl/notesout.xsl
       echo
       echo

else
	echo "The notes have been kept unchanged."
	echo
	echo

fi

return
}    



changeColor(){
params=$#
if [ $params = "3" ]; then
    infile="../Data/$1_Copy$2_*.xml"
    tempfile="../Data/$1_Copy$2_*.tmp"
elif [ $params = "4" ]; then
    infile="../Data/$1_Copy$2_$3_*.xml"
    tempfile="../Data/$1_Copy$2_$3_*.tmp"
fi
echo "infile is $infile."

clear
echo "When an entry is overriden its color is changed to red"
echo "When a note is entered on a line its color,"
echo "if not overriden, is changed to dark blue."
echo "Red and dark blue print like black."
echo "You may change the color of an overriden entry"
echo "or an entry containing a note"
echo "or any entry"
echo "by using this fuction."
echo
echo "Do you wish to change the color of the text of this entry?"
echo "Enter y or n"
read this
if yOrn "$this"

then
    echo "Please enter the color you wish::"
    read color
    java $XALANJAVAJAR org.apache.xalan.xslt.Process -in $infile -xsl ../BaseXsl/colorin.xsl -PARAM shade $color -out $tempfile
    mv $tempfile $infile
    echo
    cat $infile
    clear
    echo
    echo "The color of the text is now:"
    java $XALANJAVAJAR org.apache.xalan.xslt.Process -in $infile -xsl ../BaseXsl/colorout.xsl
    echo
    return		
else
    clear
    echo " "
    echo "The color value has been kept unchanged:"
    echo "The color value is:"
    java $XALANJAVAJAR org.apache.xalan.xslt.Process -in $infile -xsl ../BaseXsl/colorout.xsl
    echo

    return
    
fi    

return
}    




check_copy_existence(){
    for file in ../2Fo/$1_Copy$2*
    do
	if [ -e $file ]
	then
	    echo "     $2) Copy$2"
	    break;
	fi
    done	
    }


set_copy_number() {
    while true;
    do
	clear
	echo "Choose the copy with which you wish to work:"
	check_copy_existence $1 00
        check_copy_existence $1 01
	check_copy_existence $1 02
	check_copy_existence $1 03
	check_copy_existence $1 04
	check_copy_existence $1 05
	check_copy_existence $1 06
	check_copy_existence $1 07
	check_copy_existence $1 08
	check_copy_existence $1 09
	check_copy_existence $1 10
	check_copy_existence $1 11
	check_copy_existence $1 12
	check_copy_existence $1 13
	check_copy_existence $1 14
	check_copy_existence $1 15
	check_copy_existence $1 16
	check_copy_existence $1 17
        check_copy_existence $1 18
	check_copy_existence $1 19
	check_copy_existence $1 20
        echo "    new) Create a new copy of $1."
	echo "     rm) Remove a copy of $1."
	echo "      q) Return to previous menu."

	echo
	echo "There ought to be an 00 copy."
	echo "If there is no 00 copy,"
	echo "it means $1 is not yet"
	echo "part of the tax-bash program."
	echo
        echo "Enter the number of the copy with which you wish to work."
	echo
	echo "If you wish to create a new copy of $1, then enter new."
	echo
	echo "If you wish to remove a copy of $1, then enter rm."
	echo
	echo "To return to the previous menu enter q."
	echo
	echo "  Enter your choice:"
        read copy_number
 

	case $copy_number in
	 00) choice00NotAllowed $copy_number;;
         01) set_menu_choices $1 $copy_number;;
         02) set_menu_choices $1 $copy_number;;     
         03) set_menu_choices $1 $copy_number;;
         04) set_menu_choices $1 $copy_number;;
         05) set_menu_choices $1 $copy_number;;
         06) set_menu_choices $1 $copy_number;;
         07) set_menu_choices $1 $copy_number;;
         08) set_menu_choices $1 $copy_number;;
         09) set_menu_choices $1 $copy_number;;
         10) set_menu_choices $1 $copy_number;;
         11) set_menu_choices $1 $copy_number;;
         12) set_menu_choices $1 $copy_number;;
         13) set_menu_choices $1 $copy_number;;
         14) set_menu_choices $1 $copy_number;;
         15) set_menu_choices $1 $copy_number;;
         16) set_menu_choices $1 $copy_number;;
         17) set_menu_choices $1 $copy_number;;
         18) set_menu_choices $1 $copy_number;;
         19) set_menu_choices $1 $copy_number;;
         20) set_menu_choices $1 $copy_number;;
        new) create_new_copy $1;;
	 rm) removeForm $1 $2;;
         q) break;;
	 
	esac
	done

}



create_new_copy() {
    while true;
    do
	clear
	echo "These are the copies of "$1" that currently exist:"
	check_copy_existence $1 00
        check_copy_existence $1 01
	check_copy_existence $1 02
	check_copy_existence $1 03
	check_copy_existence $1 04
	check_copy_existence $1 05
	check_copy_existence $1 06
	check_copy_existence $1 07
	check_copy_existence $1 08
	check_copy_existence $1 09
	check_copy_existence $1 10
	check_copy_existence $1 11
	check_copy_existence $1 12
	check_copy_existence $1 13
	check_copy_existence $1 14
	check_copy_existence $1 15
	check_copy_existence $1 16
	check_copy_existence $1 17
        check_copy_existence $1 18
	check_copy_existence $1 19
	check_copy_existence $1 20
	echo
	echo "There ought to be an 00 copy."
	echo "If there is no 00 copy,"
	echo "it means this Form is not yet"
	echo "part of the tax-bash program."
	echo
	echo "The 00 copy should be kept pristine."
	echo "Choosing 00 does nothing."
	echo
	echo "Enter the number of the copy you wish to create."
        echo "This is usually the next number in the series."
	echo "01,02,03,etc. up to 20"
	echo
	echo "If you DO NOT wish to create a new copy,"
	echo "enter q to return to the previous menu."
	echo

       read copynumber

       case $copynumber in
         00) choiceNotAllowed $copynumber;;
         01) ../NewCopy/2focopy$copynumber $1
             ../NewCopy/xslcopy$copynumber $1
	     ../NewCopy/datacopy$copynumber $1
	     refreshTl
	     set_menu_choices $1 $copynumber;;
         02) ../NewCopy/2focopy$copynumber $1
	     ../NewCopy/xslcopy$copynumber $1
             ../NewCopy/datacopy$copynumber $1
	     refreshTl
	     set_menu_choices $1 $copynumber;;
         03) ../NewCopy/2focopy$copynumber $1
	     ../NewCopy/xslcopy$copynumber $1
             ../NewCopy/datacopy$copynumber $1
	     refreshTl
	     set_menu_choices $1 $copynumber;;
         04) ../NewCopy/2focopy$copynumber $1
	     ../NewCopy/xslcopy$copynumber $1
             ../NewCopy/datacopy$copynumber $1
	     refreshTl
	     set_menu_choices $1 $copynumber;;
         05) ../NewCopy/2focopy$copynumber $1
	     ../NewCopy/xslcopy$copynumber $1
             ../NewCopy/datacopy$copynumber $1
	     refreshTl
	     set_menu_choices $1 $copynumber;;
         06) ../NewCopy/2focopy$copynumber $1
	     ../NewCopy/xslcopy$copynumber $1
             ../NewCopy/datacopy$copynumber $1
	     refreshTl
	     set_menu_choices $1 $copynumber;;
         07) ../NewCopy/2focopy$copynumber $1
	     ../NewCopy/xslcopy$copynumber $1
             ../NewCopy/datacopy$copynumber $1
	     refreshTl
	     set_menu_choices $1 $copynumber;;
         08) ../NewCopy/2focopy$copynumber $1
	     ../NewCopy/xslcopy$copynumber $1
             ../NewCopy/datacopy$copynumber $1
	     refreshTl
	     set_menu_choices $1 $copynumber;;
         09) ../NewCopy/2focopy$copynumber $1
	     ../NewCopy/xslcopy$copynumber $1
             ../NewCopy/datacopy$copynumber $1
	     refreshTl
	     set_menu_choices $1 $copynumber;;
         10) ../NewCopy/2focopy$copynumber $1
	     ../NewCopy/xslcopy$copynumber $1
             ../NewCopy/datacopy$copynumber $1
	     refreshTl
	     set_menu_choices $1 $copynumber;;
         11) ../NewCopy/2focopy$copynumber $1
	     ../NewCopy/xslcopy$copynumber $1
             ../NewCopy/datacopy$copynumber $1
	     refreshTl
	     set_menu_choices $1 $copynumber;;
         12) ../NewCopy/2focopy$copynumber $1
	     ../NewCopy/xslcopy$copynumber $1
             ../NewCopy/datacopy$copynumber $1
	     refreshTl
	     set_menu_choices $1 $copynumber;;
         13) ../NewCopy/2focopy$copynumber $1
	     ../NewCopy/xslcopy$copynumber $1
             ../NewCopy/datacopy$copynumber $1
	     refreshTl
	     set_menu_choices $1 $copynumber;;
         14) ../NewCopy/2focopy$copynumber $1
	     ../NewCopy/xslcopy$copynumber $1
             ../NewCopy/datacopy$copynumber $1
	     refreshTl
	     set_menu_choices $1 $copynumber;;
         15) ../NewCopy/2focopy$copynumber $1
	     ../NewCopy/xslcopy$copynumber $1
             ../NewCopy/datacopy$copynumber $1
	     refreshTl
	     set_menu_choices $1 $copynumber;;
         16) ../NewCopy/2focopy$copynumber $1
	     ../NewCopy/xslcopy$copynumber $1
             ../NewCopy/datacopy$copynumber $1
	     refreshTl
	     set_menu_choices $1 $copynumber;;
         17) ../NewCopy/2focopy$copynumber $1
	     ../NewCopy/xslcopy$copynumber $1
             ../NewCopy/datacopy$copynumber $1
	     refreshTl
	     set_menu_choices $1 $copynumber;;
         18) ../NewCopy/2focopy$copynumber $1
	     ../NewCopy/xslcopy$copynumber $1
             ../NewCopy/datacopy$copynumber $1
	     refreshTl
	     set_menu_choices $1 $copynumber;;
         19) ../NewCopy/2focopy$copynumber $1
	     ../NewCopy/xslcopy$copynumber $1
             ../NewCopy/datacopy$copynumber $1
	     refreshTl
	     set_menu_choices $1 $copynumber;;
         20) ../NewCopy/2focopy$copynumber $1
	     ../NewCopy/xslcopy$copynumber $1
             ../NewCopy/datacopy$copynumber $1
	     refreshTl
	     set_menu_choices $1 $copynumber;;
	 q ) break;;
	 * ) echo "Choice not recognized."
	     echo "The menu will reappear in 2 seconds."
	     sleep 2;;
	    
	esac
    done
}




removeForm(){
        echo "Please enter the number of the copy"
	echo "   of Form&1 you wish to remove."
	read number
	echo "You are about to remove copy"$number" of "$1"."
	echo "These are the files that will be removed:"



	dir ../2Fo/$1_Copy$number*
	dir ../MyVariables/v$1_Copy$number*
	dir ../MyLines/l$1_Copy$number*
	dir ../Output/all.xml
	dir ../Output/$1_Copy$number*
	
	echo "Are you sure you want to remove these files?"
	echo "Enter y or n."
	read this
	if yOrn "$this"
	   then
	     rm ../2Fo/$1_Copy$number*
	     rm ../MyVariables/v$1_Copy$number*
	     rm ../MyLines/l$1_Copy$number*
	     rm ../Output/all.xml
	     rm ../Output/$1_Copy$number*

	     ../BaseXsl/maketaxlogicXsl.sh
	     refreshTl
	    
else
	     echo "$1_Copy$number will not be removed."
	fi     
}

importText(){

for file in $(dir ../Data/$1_Copy$2_*_text.xml)
do
    cp ~/TB/PW/T22/$file ../Data/
done
set_menu_choices $1 $2
}



set_menu_choices() {
    while true;
    do
	clear
	echo "Actions to be taken on "$1"_Copy"$2"."
	echo
	echo "  0) Import last years text for this form."
	echo "  1) Refresh data"
	echo "  2) Enter or alter data."
	echo "  3) Show form, schedule, or worksheet."
	echo	
	echo "  q) Return to previous menu."

        echo "Please enter your choice, then press return."
        read action_choice
	

        case $action_choice in
	   0) importText $1 $2;;   
	   1) refreshTl $1 $2;;
           2) set_$1_line_data_choice $1 $2;;
           3) showForm2 $1 $2;;
           q) break;;
        esac
    done
    }




set_schedule_choice() {
while true;
do
  clear
  echo "Schedules :"
  echo
  echo "       1) Schedule 1"
  echo "       3) Schedule 3"
  echo "       a) Schedule A"
  echo "       b) Schedule B"
  echo "       c) Schedule C"
  echo "       d) Schedule D"  
  
  echo "       q) Return to Main Menu"
  echo
  echo "Please enter the letter(s) of your choice then press return."
  read sched_choice

    case $sched_choice in
          1) set_copy_number  Sched1		;;
          2) set_copy_number  Sched2		;;
          3) set_copy_number  Sched3		;;
          a) set_copy_number  SchedA		;;
          b) set_copy_number  SchedB		;;
          c) set_copy_number  SchedC		;;
          d) set_copy_number  SchedD		;;
          h) set_copy_number  SchedH		;;
      1041k) set_copy_number  Form1041SchedK1	;;
      1065k) set_copy_number  Form1065SchedK1	;;
     1065Bk) set_copy_number  Form1065BSchedK1	;;
     1120Sk) set_copy_number  Form1120SSchedK1	;; 
      8865k) set_copy_number  Form8865SchedK1	;;
         se) set_copy_number  SchedSE		;;

          q) break;;	
    esac
done
}




set_form_choice() {
while true;
do
  clear
  echo "Forms :"
  echo
  echo "   1040)  U.S. Individual Income Tax Return" 
  echo
  echo
  echo
  echo "   1099div)  Dividends and Distributions"
  echo "   1099int)  Interest Income"
  echo "   1099r)    Distributions from Pensions, Annuities, Retirement etc."
  echo "   1099g)    Certain Government Payments"
  echo "   1099ssa)  SSA Benefit Statemen"
  echo  
  echo "   w2)    Wage and Tax Statement"
  echo
  echo "   bkg) background"
  echo
  echo "   q)     Return to Main Menu"
  echo
  echo "Please enter the letter(s) of your choice then press return."
  read form_choice
  
    case $form_choice in

      1040)      set_copy_number  Form1040;;
      1116)      set_copy_number  Form1116;;
      2106)      set_copy_number  Form2106;;
      2439)      set_copy_number  Form2439;;
      2441)      set_copy_number  Form2441;;
      3800)      set_copy_number  Form3800;;
      3903)      set_copy_number  Form3903;;
      4137)      set_copy_number  Form4137;;
      4562)      set_copy_number  Form4562;;
      4868)      set_copy_number  Form4868;;
      4797)      set_copy_number  Form4797;;
      4952)      set_copy_number  Form4952;;
      4972)      set_copy_number  Form4972;;
      5329)      set_copy_number  Form5329;;
      5405)      set_copy_number  Form5405;;
      5695)      set_copy_number  Form5695;;
      6251)      set_copy_number  Form6251;;
      6252)      set_copy_number  Form6252;;    
      8801)      set_copy_number  Form8801;;
      8812)      set_copy_number  Form8812;;
      8814)      set_copy_number  Form8814;;
      8815)      set_copy_number  Form8815;;
      8829)      set_menu_choices Form8829;;
      8863)      set_copy_number  Form8863;;
      8880)      set_copy_number  Form8880;;
      8885)      set_copy_number  Form8885;;
      8888)      set_copy_number  Form8888;;
      8889)      set_copy_number  Form8889;;
      8903)      set_copy_number  Form8903;;
      8917)      set_copy_number  Form8917;;
      8919)      set_copy_number  Form8919;;
      8949a)     set_copy_number  Form8949a;;
      8949b)     set_copy_number  Form8949b;;
      8949c)     set_copy_number  Form8949c;;
      8959)      set_copy_number  Form8959;;
      8960)      set_copy_number  Form8960;;
      8962)      set_copy_number  Form8962;;
      1099b)     set_copy_number  Form1099b;;
      1099div)   set_copy_number  Form1099div;;
      1099int)   set_copy_number  Form1099int;;	
      1099r)     set_copy_number  Form1099r;;	
      1099g)     set_copy_number  Form1099g;;
      1099ssa)   set_copy_number  Form1099ssa;;
      w2)        set_copy_number  w2;;	
      bkg)       set_copy_number  Bkg;;      
      q)         break;;
    esac
done

}



makeWksts(){
	../NewCopy/2focopy01  top
	../NewCopy/xslcopy01  top
	../NewCopy/datacopy01 top
	../NewCopy/2focopy01   bottom
	../NewCopy/xslcopy01   bottom
	../NewCopy/datacopy01  bottom
	../NewCopy/2focopy01    QDCGTaxWkst
	../NewCopy/xslcopy01    QDCGTaxWkst
	../NewCopy/datacopy01   QDCGTaxWkst
	../NewCopy/2focopy01     QDCGaTaxWkst
	../NewCopy/xslcopy01     QDCGaTaxWkst
	../NewCopy/datacopy01    QDCGaTaxWkst
	../NewCopy/2focopy01      SchedDTaxWkst
	../NewCopy/xslcopy01      SchedDTaxWkst
	../NewCopy/datacopy01     SchedDTaxWkst
	../NewCopy/2focopy01       SchedDaTaxWkst
	../NewCopy/xslcopy01       SchedDaTaxWkst
	../NewCopy/datacopy01      SchedDaTaxWkst
	../NewCopy/2focopy01   Bkg
	../NewCopy/xslcopy01   Bkg
	../NewCopy/datacopy01  Bkg

	refreshTl

}


set_wkst_choice() {
while true;
do
  clear
  echo "Worksheets :"
  echo
  echo "    cap)   Capital Loss Carryover Worksheet"
  echo "    top)   Top of Foreign Earned Income Tax Worksheet."
  echo " bottom)   Bottom of Foreign Earned Income Tax Worksheet."
  echo "   qdcg)   Qualified Dividends & Capital Gain Tax Worksheet-f1040-line44."
  echo "  qdcga)   Qualified Dividents & Capital Gain Alternative Tax Worksheet." 
  echo "   schd)   Schedule D Tax Worksheet."
  echo "  schda)   Schedule D Alternative Tax Workssheet."
  echo "    ssa)   Social Security Benefit Statement"
  echo "    sst)   Social Security Tax Worksheet."
  echo "   1250)   Unrecaptured Section 1250 Gain Worksheet."
  
  
  echo "   q)     Return to Main Menu"
  echo
  echo "Please enter the letter(s) of your choice then press return."
  read wkst_choice

    case $wkst_choice in

      cap)   set_copy_number  cap	     01;;		 
      fei)   set_copy_number  FEITaxWkst     01;;
      top)   set_copy_number  top            01;;
   bottom)   set_copy_number  bottom         01;;   
     ln10)   set_copy_number  WSln10         01;;
     qdcg)   set_copy_number  QDCGTaxWkst    01;;
    qdcga)   set_copy_number  QDCGaTaxWkst   01;; 
     schd)   set_copy_number  SchedDTaxWkst  01;;
    schda)   set_copy_number  SchedDaTaxWkst 01;;
    sales)   set_copy_number  WSSchASalesTax 01;;
      ssa)   set_copy_number  Form1099ssa    01;;
      sst)   set_copy_number  SST            01;;
     1250)   set_copy_number  UG1250Wkst     01;;
        q)   break;;
    esac
done
 
}




set_data_form_choice() {
while true;
do
  clear
  echo "Forms for which to enter and edit data :"
  echo
  echo "   bkg) background"
  echo "   a) Schedule A"
  echo "   c) Schedule C"
  echo "   1040) Form 1040"
  echo 
  echo "   div01)Form 1099DIV_Copy01"
  echo "   div02)Form 1099DIV_Copy02"
  echo "   div03)Form 1099DIV_Copy03"
  echo "   div04)Form 1099DIV_Copy04"
  echo "   div05)Form 1099DIV_Copy05"
  echo ""
  echo "   int01)Form 1099INT_Copy01"
  echo "   int02)Form 1099INT_Copy02"
  echo "   int03)Form 1099INT_Copy03"
  echo "   int04)Form 1099INT_Copy04"
  echo "   int05)Form 1099INT_Copy05"
  echo "   int06)Form 1099INT_Copy06"
  echo "   int08)Form 1099INT_Copy07"
  echo "   int08)Form 1099INT_Copy08"
  echo "   int09)Form 1099INT_Copy09"
  echo "   int10)Form 1099INT_Copy10"
  echo "   int11)Form 1099INT_Copy11"
  echo "   int12)Form 1099INT_Copy12"
  echo "   int13)Form 1099INT_Copy13"
  echo "   int14)Form 1099INT_Copy14"
  echo 
  echo "   r01)  Form 1099R_Copy01"
  echo "   r02)  Form 1099R_Copy02"
  echo "   r03)  Form 1099R_Copy03"
  echo "   r04)  Form 1099R_Copy04"
  echo "   r05)  Form 1099R_Copy05" 
  echo "   r06)  Form 1099R_Copy06"
  echo "   r07)  Form 1099R_Copy07"
  echo 
  echo "   g01)  Form 1099G_Copy01"
  echo "   g02)  Form 1099G_Copy02"
  echo "   g03)  Form 1099G_Copy03"
  echo "   g04)  Form 1099G_Copy04"
  echo "   g05)  Form 1099G_Copy05" 
  echo ""
  echo "   4562) Form 4562"
  echo "   4868) Form 4868"
  echo "   6251) Form 6251"
  echo "   6252) Form 6252"
  echo "   8829) Form 8829"  
  echo 
  echo "     q)  Return to Previous Menu"
  echo
  echo "Please enter the letter(s) of your choice then press return."
  read data_form_choice

    case $data_form_choice in

      bkg) set_background_line_data_choice;;	
      a) set_schedA_line_data_choice;;
      c) set_schedC_line_data_choice;;

      1040) set_form1040_line_data_choice;;

      div01)  set_form1099div01_line_data_choice;;
      div02)  set_form1099div02_line_data_choice;;
      div03)  set_form1099div03_line_data_choice;;
      div04)  set_form1099div04_line_data_choice;;
      div05)  set_form1099div05_line_data_choice;;

      int01)  set_form1099int01_line_data_choice;;
      int02)  set_form1099int02_line_data_choice;;
      int03)  set_form1099int03_line_data_choice;;
      int04)  set_form1099int04_line_data_choice;;
      int05)  set_form1099int05_line_data_choice;;
      int06)  set_form1099int06_line_data_choice;;
      int07)  set_form1099int07_line_data_choice;;
      int08)  set_form1099int08_line_data_choice;;
      int09)  set_form1099int09_line_data_choice;;
      int10)  set_form1099int10_line_data_choice;;
      int11)  set_form1099int11_line_data_choice;;
      int12)  set_form1099int12_line_data_choice;;
      int13)  set_form1099int13_line_data_choice;;
      int14)  set_form1099int14_line_data_choice;;
      
    
      r01)    set_form1099r01_line_data_choice;;
      r02)    set_form1099r02_line_data_choice;;
      r03)    set_form1099r03_line_data_choice;;
      r04)    set_form1099r04_line_data_choice;;
      r05)    set_form1099r05_line_data_choice;;
      r06)    set_form1099r06_line_data_choice;;
      r07)    set_form1099r07_line_data_choice;;
	
      g01)    set_form1099g01_line_data_choice;;
      g02)    set_form1099g02_line_data_choice;;
      g03)    set_form1099g03_line_data_choice;;
      g04)    set_form1099g04_line_data_choice;;
      g05)    set_form1099g05_line_data_choice;;

      4562)   set_form4562_line_data_choice;;
      4868)   set_form4868_line_data_choice;;
      6251)   set_form6251_line_data_choice;;
      6252)   set_form6252_line_data_choice;;
      8829)   set_form8829_line_data_choice;;
      
      q)      break;;
    esac
done
}




set_line_menu_text() {
while true;
do

 echo
 echo  " 1) Show local instructions for this line."   
 echo  " 2) show IRS instructions for this line" 
 echo  " 3) Show current contents of the line"
 echo  " 4) Edit the text of this line."
 echo  " 5) Redisplay the form."
 echo  " 5a)Change the color of this line."
 echo  " 6) Comes from?"
 echo  " q) quit"

 echo "Please enter number of your choice and press Enter."
 read action_choice

 case $action_choice in
        1) showInstructions $1 $2 $3 $4;;
	2) showIRSinstructions $1 $2 $3 $4;;
	3) showDataFile $1 $2 $3;;
        4) edit_textline $1 $2 $3;;
        5) showFormLocal $1 $2 $3;;
	5a)changeColor $1 $2 $3 $4;;
	6) params=$#
	   echo $params
	   if [ "$params" = "3" ]; then
	       infile="../Data/$1_$2_text.xml"
	       tempfile="../Data/$1_$2_text.tmp"
	   elif [ "$params" = "4" ]; then
	       infile="../Data/$1_$2_$3_text.xml"
	       tempfile="../Data/$1_$2_$3_text.tmp"
	   fi
	   echo "infile is $infile tempfile is $tempfile"

	   echo $infile
	   echo "This line comes from:"
	   foo=$(sed -n '/<from>/s/<from>//;s/<\/from>//p' $infile)
	   echo $foo
	   select fname in $foo
	   do
               echo "You have selected" $fname \($REPLY\)
	       par=$fname
	       parminus=${par#*_}
	       par1=${parminus%%_*}
	       echo $par1
	       parminus2=${parminus#*_}
	       par2=${parminus2%%_*}
	       echo $par2
	       par3=${parminus2##*_}
	       echo $par3
	       echo $par3

	       echo $par3
	       echo $par2
	       echo $par1
	       echo $par1 $par2 $par3
	       set $(echo $par1 $par2 $par3)
               set_line_menu_text $1 $2 $3
	       break;
            done
	   ;;
	   q) break;;

 esac

done

}



set_line_menu_number() {
while true;
do
 clear
 echo "The following actions can be taken on $1_$2_$3"
 echo   
 echo  "  1) show local instructions for this line"
 echo  "  2) show IRS instructions for this line" 
 echo  "  3) show current contents of the line"
 echo  "  4) specify accounts from which to draw data for this line"
 echo  "  5) enter number directly or override value obtained in (4)"
 echo  "  6) redisplay the form, Schedule, or worksheet"
 echo  "  7) Enter notes about this line"

 echo  " q) quit"
 echo "Please enter number of your choice and press Enter."
 read action_choice
  
 case $action_choice in
        1) showInstructions    $1 $2 $3 $4;;
	2) showIRSinstructions $1 $2 $3 $4;;
	3) showDataFile	       $1 $2 $3 $4;;
        4) edit-numberline     $1 $2 $3 $4;;
        5) edit-override       $1 $2 $3 $4;;
	6) showForm	       $1 $2 $3 $4;;
        7) enterNotes	       $1 $2 $3 $4;;

	q) break;;
    esac

done

}



set_line_menu_nav() {
while true;
do

    echo
 echo  " 1) Show local instructions for this line."   
 echo  " 2) show IRS instructions for this line" 
 echo  " 3) Show current contents of the line"
 echo  " 4) Comes from"
 echo  " 5) Goes to"

 echo  " q) quit"
 echo "Please enter number of your choice and press Enter."
 read action_choice
  
 case $action_choice in
        1) showInstructions	 $1 $2 $3 $4;;
	2) showIRSinstructions	 $1 $2 $3 $4;;
	3) showDataFile		 $1 $2 $3 $4;;
	4) comesFrom		 $1 $2 $3 $4;;
	5) goesTo		 $1 $2 $3 $4;;
	q) break;;
    esac

done

}



set_menu_choice() {
while true;
  do     
  echo
  echo "Welcome to Tax-bash."
  echo
  echo "   0)  Update (Download program again)"
  echo "   1)  Import last years return."
  echo "   2)  Import last year's text files."
  echo "   3)  Import data from GnuCash."
  echo
  echo "   ln) List the names of all of the accounts in your GnuCash data."
  echo "   at) List the transactions in a specified account."
  echo
  echo "   4)  Initialize or refresh all of your data."
  echo 
  echo "   f)  Show choice of Forms."
  echo "   s)  Show choice of Schedules."
  echo "   w)  Show choice of Worksheets."
echo 
  echo "   q) Quit"
 
  echo "Please enter the number or letter(s) of your choice then press return."
  read menu_choice

    case "$menu_choice" in
      0) ../../downloadT22.sh
      	 update;;	 
      1) importLastYrReturn;;
      2) importLastYrText;;
      3) importGnuCash;;
      4) refreshAll;;

      ln) listAccounts;;
      at) oneAcct;;
      
      f)  set_form_choice;;	
      s)  set_schedule_choice;;
      w)  makeWksts
          set_wkst_choice;;

      q)  exit;;
      *)  echo "Sorry, choice not recognized."
    esac
  done  
}






update(){

for file in $(dir ../2Fo/)
do
    foo=$file
    echo $foo
    bar=${foo%%.2fo*}
    echo $bar
    copy=${bar##*Copy}
    echo $copy
    form=${foo%%_Copy*}
    echo $form		  

	
    case $copy in
	00) ;;
	01) echo "Copy01 invoked."
	    ../NewCopy/2focopy01 $form
	    ../NewCopy/xslcopy01 $form
	    ../NewCopy/datacopy01 $form
	    ;;
	02) echo "Copy02 invoked."
	    ../NewCopy/2focopy02 $form
	    ../NewCopy/xslcopy02 $form
	    ../NewCopy/datacopy02 $form
	    ;;
	03) ../NewCopy/2focopy03 $form
	    ../NewCopy/xslcopy03 $form
	    ../NewCopy/datacopy03 $form
	    ;;
	04) ../NewCopy/2focopy04 $form
	    ../NewCopy/xslcopy04 $form
	    ../NewCopy/datacopy04 $form
	    ;;
	05) ../NewCopy/2focopy05 $form
	    ../NewCopy/xslcopy05 $form
	    ../NewCopy/datacopy05 $form
	    ;;
	06) ../NewCopy/2focopy06 $form
	    ../NewCopy/xslcopy06 $form
	    ../NewCopy/datacopy06 $form
	    ;;
	07) ../NewCopy/2focopy07 $form
	    ../NewCopy/xslcopy07 $form
	    ../NewCopy/datacopy07 $form
	    ;;
	08) ../NewCopy/2focopy08 $form
	    ../NewCopy/xslcopy08 $form
	    ../NewCopy/datacopy08 $form
	    ;;
	09) ../NewCopy/2focopy09 $form
	    ../NewCopy/xslcopy09 $form
	    ../NewCopy/datacopy09 $form
	    ;;
	10) ../NewCopy/2focopy10 $form
	    ../NewCopy/xslcopy10 $form
	    ../NewCopy/datacopy10 $form
	    ;;
	11) ../NewCopy/2focopy11 $form
	    ../NewCopy/xslcopy11 $form
	    ../NewCopy/datacopy11 $form
	    ;;
	12) ../NewCopy/2focopy12 $form
	    ../NewCopy/xslcopy12 $form
	    ../NewCopy/datacopy12 $form
	    ;;
	13) ../NewCopy/2focopy13 $form
	    ../NewCopy/xslcopy13 $form
	    ../NewCopy/datacopy13 $form
	    ;;
	14) ../NewCopy/2focopy14 $form
	    ../NewCopy/xslcopy14 $form
	    ../NewCopy/datacopy14 $form
	    ;;
	15) ../NewCopy/2focopy15 $form
	    ../NewCopy/xslcopy15 $form
	    ../NewCopy/datacopy15 $form
	    ;;
	16) ../NewCopy/2focopy16 $form
	    ../NewCopy/xslcopy16 $form
	    ../NewCopy/datacopy16 $form
	    ;;
	17) ../NewCopy/2focopy17 $form
	    ../NewCopy/xslcopy17 $form
	    ../NewCopy/datacopy17 $form
	    ;;
	18) ../NewCopy/2focopy18 $form
	    ../NewCopy/xslcopy18 $form
	    ../NewCopy/datacopy18 $form
	    ;;
	19) ../NewCopy/2focopy19 $form
	    ../NewCopy/xslcopy19 $form
	    ../NewCopy/datacopy19 $form
	    ;;
	20) ../NewCopy/2focopy20 $form
	    ../NewCopy/xslcopy20 $form
	    ../NewCopy/datacopy20 $form
	    ;;

    esac
		
done	
}





description(){
    while true;
    do
    clear
    echo
    echo "1) View description of tax-bash"
    echo "   and how to use it."
    echo
    echo "q) quit"
    echo
    echo "Enter q to return to the previous menu."
    read choice
    
    case "$choice" in
        1)viewReadMe;;
	q) break;;
    esac
done
    
}




dependencies(){
    while true;
    do
    clear
    echo
    echo "The tax-bash program uses the following programs:"
    echo
    echo "bash    : bash is the shell in which tax-bash is written."
    echo "sed     : sed is probably already be installed by your distsribution."
    echo "awk     : awk is probably already be installed by your distribution."
    echo "m4      : m4 needs to be installed."
    echo "xalan   : The java version is used (Not the C++ version) because"
    echo "          when I last checked the C++ version did not include "
    echo "          the format-number() function used extensively in tax-bash"
    echo "fop     : The apache formating engine is used."
    echo "qpdfview: This program works very well for displaying the forms."
    echo "X11     : This windowing system is needed by qpdfview."
    echo
    echo "These programs must be installed for tax-bash to work."
    echo
    echo "q)  Enter q to return to the previous menu."
    read choice
    
    case "$choice" in
	q) break;;
    esac
done

}




variables(){
    while true;
    do
    clear
    echo
    echo "The tax-bash program depends on several global variables:"
    echo "They are best set in the file ~/.bashrc"
    echo "so that they are set whenever you restart your computer."
    echo
    echo "The first is GNUCASHFILES which should be set to"
    echo "the path to the backup files of your GnuCash program."
    echo "On my computer, the path is"
    echo "  ~/.gnucash.data"
    echo "This variable is best set in ~/.bashrc"
    echo "To do that add the following 2 lines to the end of ~/.bashrc:"
    echo "  GNUCASHFILES='~/.gnucash.data"
    echo "  export GNUCASHFILES"
    echo
    echo "The second is XALANJAVAJAR which should be set to"
    echo "the class path to the xalan jar file."
    echo "On my computer, the value is"
    echo "  '-cp /usr/share/java/xalan2.jar'"
    echo "This variable is also best set in ~/.bashrc"
    echo "How to do this is described under choice 3) in the previous menu."
    echo
    echo "The third variable is PATH"
    echo "Tax-bash needs to use fop"
    echo "Therefore, fop should be in your PATH variable."
    echo "How to do this is described under choice 4) in the previous menu."
    echo
    echo "Enter q to return to the previous menu."
    read choice
    
    case "$choice" in
	q) break;;
    esac
done

}
    


    
setupfop(){
    while true;
    do
   clear
    echo "tax-bash needs to know the path to fop."
    echo
    echo "In my version of Ubuntu there is a bash file "fop" in the bin directory."
    echo "This is reached first in the standard PATH variable."
    echo "It works OK, although it does give a warning about 'sun'."
    echo "I suggest that you not use this version."
    echo
    echo "I suggest that you control which version of fop you use."
    echo "Do this by downloading this version and then"
    echo "put the path to it at the start of your PATH variable."
    echo
    echo "The following steps will achieve that:"
    echo
    echo  "Download from the Apache FOP website"
    echo "the most recent tarball which currently is"
    echo "  fop-2.10-bin.tar.gz"
    echo
    echo "Move this tarball from ~/Downloads to the directory of your choice."
    echo "I created the directory ~/Fop-2.10 and moved the tarball there."
    echo
    echo "Change directory into ~/Fop-2.10 and issue the following command:"
    echo "  tar -xvfz fop-2.10-bin.tar.gz"
    echo
    echo "This will create the directory fop-2.10 under ~/Fop-2.10"
    echo "and unpack the fop files into it."
    echo
    echo "The path to the executive file becomes:"
    echo "  ~/Fop-2.610/fop-2.10/fop"
    echo
    echo "The final step was to add this path to the start"
    echo "of your global variable PATH"
    echo "   PATH=~/Fop-2.10/fop-2.10/fop:$PATH"
    echo
    echo "You can do this each time you run tax-bash"
    echo "or you can add the following 2 lines to the end of ~/.bashrc"
    echo "  PATH=~/Fop-2.10/fop-2.10/fop:$PATH"
    echo "  export PATH"
    echo
    echo "Enter q to return to the previous menu."
	read choice

	case "$choice" in
	    q) break;;
	esac
    done
    

}




setupxalan(){
    while true;
    do
    clear
			
    echo " tax-bash needs to use the java version of xalan."
    echo " This is because the C(++) version does not implement"
    echo " format-number() which tax-bash uses extensively."
    echo
    echo " The following steps will achieve that:"
    echo
    echo " Download from the Apache Xalan website"
    echo " the most recent tarball which currently is"
    echo "   xalan-j_2_7_3.tar.gz"
    echo
    echo " Move this tarball from ~/Downloads to the directory of your choice."
    echo " I created the directory ~/Xalan-j_2_7_3/ and moved the tarball there."
    echo
    echo " Change directory into ~/Xalan-j_2_7_3/ and issue the following command:"
    echo " tar -xvfz xalan-j_2_7_3.tar.gz"
    echo
    echo " This will create the directory xalan-j_2_7_3/ under ~/Xalan-j_2_7_3/"
    echo " and unpacked the fop files into it."
    echo
    echo " This will also create in /usr/share/java"
    echo " the file xalan2-2.7.3.jar"
    echo
    echo " The variable XALANJAVAJAR should be set to"
    echo "   '-cp /usr/share/java/xalan2-2.7.3.jar'"
    echo " preferabllly in ~/.bashrc"
    echo " (The -cp is the option in java which sets the class path)"
    echo
    echo " Enter q to return to the previous menu."
	read choice

	case "$choice" in
	    q) break;;
	esac
    done
    

}

installqpdf(){

cat ../installqpdf.txt | less
}


initial(){
    while true;
    do
	clear
	echo
	echo "The next menu you see upon choosing"
	echo "  7)  Start using tax-bash"
	echo "from the previous menu"
	echo "will have three sets of menu choices."
	echo
	echo "The first four menu choices set up your data."
	echo
	echo "The first two involve importing last years data."
	echo "Since this is the first year you are using tax-bash,"
	echo "these first two choice currently do nothing."
	echo
	echo "The third choice imports your GnuCash data."
	echo "Be certain you have set the GNUCASHFILES variable."
	echo "(See choices 2-4 on previous menu)"
	echo "You should choose 3) to make certain you are"
	echo "using your most current gnucash data."
	echo
	echo "The next two choices allow you to look at"
	echo "your GnuCash data:"
	echo "ln: will give you a listing of all the accounts"
	echo "    in your GnuCash data."
        echo "at: will show you the transactions in any account you choose."
	echo
	echo  "The 4th choice must be performed before starting the program for the first time."
	echo  "It creates any worksheets that are necessary for the calculation of your return."
	echo  "It creates the background form (Bkg) on which to enter basic data and your filing status."
	echo  "It calculates your entire return."
	echo  "You don't need to, but you may wish to, make this choice before starting work each day."
	echo
	echo "The last 3 choices allow you to work with:"
	echo "f forms"
	echo "s schedules"
	echo "w worksheets"
	echo
	echo "q) Quit"
	echo
	echo "Enter q to return to the previous menu."
	read choice

	case "$choice" in
	    q) break;;
	esac
    done
}
    



viewReadMe(){
    cat ../README
    }




set_Bkg_line_data_choice() {
while true;
do
clear
echo "Lines in Bkg in which to enter or edit data:"
echo
echo "TFNI  )    Enter taxpayor's first name.             "
echo "TLN   )    Enter taxpayor's last name.              "
echo "TSSNoF)    Enter taxpayor's first 3 SSN digits.     "
echo "TSSNoM)    Enter taxpayor's second 2 SSN digits.    "
echo "TSSNoL)    Enter taxpayor's last 4 SSN digits.      "
echo "SFNI  )    ENter spouse's first name.               "
echo "SLN   )    Enter spouse's last name.                "
echo "SSNoF )    Enter spouse's first 3 SSN digits.       "
echo "SSSNoM)    Enter spouse's second 2 SSN digits.      "
echo "SSSNoL)    Enter spouse's last 4 SSN digits.                             "
echo "FS    )    Enter filing status.                     "
echo "Apart )    Did you (Yes or No) live apart froms spouse?             "
echo
echo "     q)    Return to Previous Menu"      
echo
echo "Please enter the letter(s) of your choice then press return."
     read Bkg_line_data_choice
echo
     case $Bkg_line_data_choice in
TFNI  )    set_line_menu_text   $1 $2  lineTFNI                             ;;
TLN   )    set_line_menu_text   $1 $2  lineTLN                              ;;
TSSNoF)    set_line_menu_text   $1 $2  lineTSSNoF                           ;;
TSSNoM)    set_line_menu_text   $1 $2  lineTSSNoM                           ;;
TSSNoL)    set_line_menu_text   $1 $2  lineTSSNoL                           ;;
SFNI  )    set_line_menu_text   $1 $2  lineSFNI                             ;;
SLN   )    set_line_menu_text   $1 $2  lineSLN                              ;;
SSNoF )    set_line_menu_text   $1 $2  lineSSNoF                            ;;
SSSNoM)    set_line_menu_text   $1 $2  lineSSSNoM                           ;;
SSSNoL)    set_line_menu_text   $1 $2  lineSSSNoL                           ;;
FS    )    set_line_menu_text   $1 $2  lineFS                               ;;
Apart )    set_line_menu_text   $1 $2  lineApart                            ;;
q     )    break;;                       
esac
done
}


set_Bkg_line_data_choice() {
while true;
do
clear
echo "Lines in Bkg in which to enter or edit data:"
echo
echo "TFNI  )    Enter taxpayor's first name.             "
echo "TLN   )    Enter taxpayor's last name.              "
echo "TSSNoF)    Enter taxpayor's first 3 SSN digits.     "
echo "TSSNoM)    Enter taxpayor's second 2 SSN digits.    "
echo "TSSNoL)    Enter taxpayor's last 4 SSN digits.      "
echo "SFNI  )    ENter spouse's first name.               "
echo "SLN   )    Enter spouse's last name.                "
echo "SSNoF )    Enter spouse's first 3 SSN digits.       "
echo "SSSNoM)    Enter spouse's second 2 SSN digits.      "
echo "SSSNoL)    Enter spouse's last 4 SSN digits.                                                                   "
echo "FS    )    Enter filing status.                     "
echo "Apart )    Did you (Yes or No) live apart froms spouse?                                                        "
echo
echo "     q)    Return to Previous Menu"      
echo
echo "Please enter the letter(s) of your choice then press return."
     read Bkg_line_data_choice
echo
     case $Bkg_line_data_choice in
TFNI  )    set_line_menu_text   $1 $2  lineTFNI                             ;;
TLN   )    set_line_menu_text   $1 $2  lineTLN                              ;;
TSSNoF)    set_line_menu_text   $1 $2  lineTSSNoF                           ;;
TSSNoM)    set_line_menu_text   $1 $2  lineTSSNoM                           ;;
TSSNoL)    set_line_menu_text   $1 $2  lineTSSNoL                           ;;
SFNI  )    set_line_menu_text   $1 $2  lineSFNI                             ;;
SLN   )    set_line_menu_text   $1 $2  lineSLN                              ;;
SSNoF )    set_line_menu_text   $1 $2  lineSSNoF                            ;;
SSSNoM)    set_line_menu_text   $1 $2  lineSSSNoM                           ;;
SSSNoL)    set_line_menu_text   $1 $2  lineSSSNoL                           ;;
FS    )    set_line_menu_text   $1 $2  lineFS                               ;;
Apart )    set_line_menu_text   $1 $2  lineApart                            ;;
q     )    break;;                       
esac
done
}
    

while true;
      do    
  clear
  echo
  echo "Welcome to Tax-bash."
  echo
  echo "0)  Read a description of the program"
  echo "1)  On which programs is tax-bash dependent?"
  echo "2)  What global variables should be set?"
  echo "3)  How to set up Xalan to use the java version."
  echo "4)  How to set up FOP"
  echo "5)  Installing qpdf"  
  echo "6)  Initial actions to take with tax-bash."
  echo "7)  Start using tax-bash"
  echo
  echo "q)  Exit the program"
  read choice

  case "$choice" in
   0) description;;   
   1) dependencies;;
   2) variables;;
   3) setupxalan;;
   4) setupfop;;
   5) installqpdf;; 
   6) initial;;
   7) set_menu_choice;;
   q) exit;;   
  esac
	
done	
    

echo "Finished"

exit 0

