#!/bin/bash
#Copyright(C) 2023, 2024 Phillips Wedemeyer
#
#This file is part of a program called Tax-bash.
#
#Tax-bash is free software: you can redistibute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#Tax-bash is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with Tax-bash.  If not, see <https://www.gnu.org/licenses/>.
#
#


downloadPdf(){
	firefox https://apps.irs.gov/app/picklist/list/formsPublications.html
	}

dirDownloadsPdf(){
    dir ~/Downloads/*$1.pdf
    echo " "
    echo "Are you ready to continue?"
    echo "If so, press y or n."
    read this
    if yOrn $this
    then
	return
    fi
}

movePdf(){
    mv ~/Downloads/*$1.pdf ../Pdf
    }

dirPdf(){
    dir ../Pdf/*.pdf
    
    echo " "
    echo "Are you ready to continue?"
    echo "If so, press y or n."
    read this
    if yOrn $this
    then
	return
    fi
}

dirInstructions(){
    dir ../Instructions/*.pdf
    echo " "
    echo "Are you ready to continue?"
    echo "If so, press y or n."
    read this
    if yOrn $this
    then
	return
    fi
}


showPdf() {
    echo "Enter the name of the form you wish to view"
    echo "(such as f1000int):"
    read form
    qpdfview  ../Pdf/$form.pdf &
#    qpdfview $1 &
}


nau(){
    ../Pdf/nautilus $1
}



pdf2jpg(){
    firefox https://www.pdf2jpg.net
}

#pdf2jpg(){
#    ../Sed/convertpdf2jpg.sh
#    firefox https://smallpdf.com/pdf-to-jpg
#    }

dirDownloads(){
    dir ~/Downloads/*.jpg
    echo " "
    echo "Are you ready to continue?"
    echo "If so, press y or n."
    read this
    if yOrn $this
    then
	return
    fi
}

unzipDownloads(){
 ../Sed/unzipDownloads.sh
}

dirimages(){
    dir ~/Downloads/images/*
    echo " "
    echo "Are you ready to continue?"
    echo "If so, press y or n."
    read this
    if yOrn $this
    then
	return
    fi
}

moveJpg(){
    mv ~/Downloads/*.jpg  ../Jpg/
    }

moveJpgFile(){
    echo "Enter the name of the file you wish to move."
    read file
    mv ~/Downloads/images/$file.jpg ../Jpg
}

dirJpg(){
    clear
    dir ../Jpg/*
    echo " "
    echo "Are you ready to continue?"
    echo "If so, press y or n."
    read this
    if yOrn $this
    then
	return
    fi
    }

rmimages(){
    rm ~/Downloads/images/*
}

rmDownloadsPdf(){
    rm ~/Downloads/*.pdf
}

removeYr(){
    for file in $(dir ../Jpg/*_20*)
    do
	echo $file
    beg=${file%%_20*}
    echo $beg
    end=${file#*_20}
    echo $end
    dest="$beg$end"
    echo $dest
    mv $file $dest
    done
}

dirFo(){
    clear
    dir ../Fo
    echo " "
    echo "Are you ready to continue?"
    echo "If so, press y or n."
    read this
    if yOrn $this
    then
	return
    fi
}

#text2input(){
    
#}

#input2data(){

#}

data2fo(){
    java $XALANJAVAJAR org.apache.xalan.xslt.Process -in ../Table/bkgdata.xml -xsl ../Table/table.xsl -out ../Fo/fBkg.fo
}


fo2pdf(){
#Note that fop always produces a .pdf file with the same name as the .fo file.    
fop ../Fo/fBkg.fo ../Pdf/fBkg.pdf
}

exportJpg(){
    cp ../Jpg/* ../../3Layout/Jpg
    cp ../Jpg/* ../../4Calc/Jpg
    cp ../Jpg/* ../../7App/Jpg
}

exportPdf(){
    cp ../Pdf/* ../../2Sequence/Pdf
    cp ../Pdf/* ../../3Layout/Pdf
    cp ../Pdf/* ../../4Calc/Pdf
    cp ../Pdf/* ../../7App/Pdf

}




    




set_menu_choices() {
while true;
  do     
  clear
  echo
  echo
  echo "   1)  Download pdf view of form from IRS to ../Pdf"
  echo "   2)  dir ../Pdf"
  echo "   3)  View the ../.pdf file."
  echo "   4)  Convert pdf to jpg and into ~/Downloads/.jpg"
  echo "   5)  dir ~/Downloads/*.jpg"
#  echo "   6)  unzip zip file to ~/Downloads/*.jpg"
#  echo "   7)  dir ~/Downloads/*"
  echo "   8)  Move ~/Downloads/*.jpg to ../Jpg"
  echo "   9)  dir ../Jpg/*"
  echo "  10)  rm ~/Downloads/*.jpg"
  echo "  11)  export ../Jpg/* to 3Layout, 4Calc, and 7App"
  echo "  12)  export ../Pdf/* to 2Sequence, 3Layout, 4Calc, and 7App"

  echo "   q) Quit"
 
  echo "Please enter the number or letter(s) of your choice then press return."
  read menu_choice

    case "$menu_choice" in

      1)  downloadPdf;;
      2)  dirPdf;;
      3)  showPdf $1;;
      4)  pdf2jpg;;
      5)  dirDownloads;;
#      6)  unzipDownloads;;
#      7)  dirimages;;
      8)  moveJpg;;
      9)  dirJpg;;
      #     10)  rmimages;;
     10)  rmDownloadsPdf;; 
     11)  exportJpg;;
     12)  exportPdf;;
      
      q)  exit;;
      *)  echo "Sorry, choice not recognized."
    esac
  done  
}

set_wksMenu_choices() {
while true;
  do     
  clear
  echo
  echo
  echo "   1)  Download $1.pdf file from IRS to ../Instructions"
  echo "   2)  dir ../Instructions"
  echo "   3)  Open ../Instructions/$1.pdf in nautilus"
  echo "       Maually go to page(s) containing the worksheet desired"
  echo "       Print the page(s) to a file in the ../Pdf directory."
  echo "       Suggested nominclature: $1.pdf"
  echo "   4)  dir ../Pdf"
  echo "   5)  view the .pdf file"
  echo "   6)  Convert .pdf to ~/Downloads/*.jpg"
  echo "   7)  Check that the .jpg files are in ~/Downloads/"
#  echo "   8)  unzip zip files to ~/Downloads/images"
#  echo "   9)  Check that .jpg files are in ~/Downloads/images/"
  echo "  10)  Move ~/Downloads/*.jpg to ../Jpg" 
  echo "  11)  dir ../Jpg/*.jpg"
#  echo "  12)  rm ~/Downloads/*.jpg"
  echo "  13)  Export ../Jpg/* to 3Layout, 4Calc, and 7App"
  echo "  14)  Export ../Pdf/* to 2Sequence, 3Layout, 4Calc and 7App"
  echo
  echo "   q) Quit"
 
  echo "Please enter the number or letter(s) of your choice then press return."
  read menu_choice

    case "$menu_choice" in

      1)  downloadPdf;;
      2)  dirInstructions;;
      3)  nautilus ../Instructions/$1.pdf;;
      4)  dirPdf $1;;
      5)  showPdf;;
      6)  pdf2jpg;;
      7)  dirDownloads;;
#      8)  unzipDownloads;;
#      9)  dirimages;;
     10)  moveJpg;;	  
     11)  dirJpg;;
#     12)  rmimages;; 
     13)  exportJpg;;
     14)  exportPdf;;
      
      q)  exit;;
      *)  echo "Sorry, choice not recognized."
    esac
  done  
}

set_tableMenu_choices() {
while true;
  do     
  clear
  echo
  echo
#  echo "   1)  Convert "$1".text to "$1".input"
#  echo "   2)  Convert "$1".input to "$1"data.xml
  echo "   3)  Convert ../Table/bkgdata.xml to ../Fo/fBkg.fo"
  echo "   4)  dir ../Fo"
  echo "   5)  Convert ../Fo/fBkg.fo to ../Pdf/fBkg.pdf."
  echo "   6)  dir ../Pdf"
  echo "   7)  view ../Pdf/fBkg.pdf" 
  echo "   8)  Convert ../Pdf/fBkg.pdf to ../Downloads/*.zip"
  echo "   9)  dir ~/Downloads/*.zip"
  echo "  10)  unzip ~/Downloads/*.zip to ~/Downloads/images/*.jpg"
  echo "  11)  dir ~/Downloads/images/*jpg" 
  echo "  12)  move ~/Downloads/images/*.jpg to ../Jpg"
  echo "  13)  dir ../Jpg"
  echo "  14)  rm ~/Downloads/images/*jpg"
  echo "  15)  export ../Jpg/* to 3Layout, 4Calc, and 7App"
  echo "  16)  export ../Pdf/* to 2Sequence, 3Layout, 4Calc, and 7App"

  echo "   q) Quit"
 
  echo "Please enter the number or letter(s) of your choice then press return."
  read tablemenu_choice

    case "$tablemenu_choice" in

#      1)  text2input $1;;
#      2)  input2data $1;;
      3)  data2fo;;
      4)  dirFo;;
      5)  fo2pdf;;
      6)  dirPdf;;
      7)  qpdfview ../Pdf/fBkg.pdf;;
      8)  pdf2jpg;;
      9)  dirDownloads;;
     10)  unzipDownloads;;
     11)  dirJpg;;
     12)  moveJpg;;
     13)  dirJpg;;
     14)  rmimages;;
     15)  exportJpg;;
     16)  exportPdf;;
      
      q)  exit;;
      *)  echo "Sorry, choice not recognized."
    esac
  done  
}




set_schedule_choice() {
while true;
do
  clear
  echo "Schedules :"
  echo
  echo "       a) Schedule A"
  echo "       b) Schedule B"
  echo "       c) Schedule C"
  echo "       d) Schedule D"
  echo "       e) Schedule E"
  echo "       f) Schedule F"
  echo "       h) Schedule H."
  echo "       j) Schedule J"
  echo "      se) Schedule SE"
  echo "     sei) Earned Income Credit"
  echo "     sse) Schedule SSE"
  echo "       r) Credit for Elderly"
  echo "       1) Schedule 1"
  echo "       2) Schedule 2"
  echo "       3) Schedule 3"
  echo "       4) Schedule 4"
  echo "       5) Schedule 5"
  echo "       6) Schedule 6"
  echo "     sk1) Schedule SK1(Form1065)" 
  echo "       q) Return to Main Menu"
  echo
  echo "Please enter the letter(s) of your choice then press return."
  read sched_choice

    case $sched_choice in
          a) set_menu_choices f1040sa;;
          b) set_menu_choices f1040sb;;
          c) set_menu_choices f1040sc;;
          d) set_menu_choices f1040sd;;
	  e) set_menu_choices f1040se;;
	  f) set_menu_choices f1040sf;;
          h) set_menu_choices f1040sh;;
	  j) set_menu_choices f1040sj;;
	  r) set_menu_choices f1040sr;;
         se) set_menu_choices f1040se;;
	se1) set_menu_choices f1040sei;;
        sse) set_menu_choices f1040sse;;
	  1) set_menu_choices f1040s1;;
	  2) set_menu_choices f1040s2;;
	  3) set_menu_choices f1040s3;;
	  4) set_menu_choices f1040s4;;
	  5) set_menu_choices f1040s5;;
	  6) set_menu_choices f1040s6;;
	sk1) set_menu-choices f1065sk1;;

          q) break;;	
    esac
done
}


set_form_choice() {
while true;
do
  clear
  echo "Forms :"
  echo
  echo "   1040)  U.S. Individual Income Tax Return"
  echo "   1040v) Payment Voucher"
  echo "   1116)  Foreign Tax Credit"
  echo "   2106)  Employee Business Expenses"          
  echo "   2439)  Notice to Shareholder of Long-Term Undistributed Capital Gains"
  echo "   2441)  Child and Dependent Care Expenses"
  echo "   2555)  Foreign Earned Income"
  echo "   3800)  General Business Credit"
  echo "   3903)  Moving Expenses"
  echo "   4137)  Social Security and Medicare Tax on Unreported Tip Income"
  echo "   4562)  Depreciation and Amortization"
  echo "   4797)  Sales of Business Property"
  echo "   4868)  Application for Automatic Extension of Time to file"
  echo "   4952)"
  echo "   4972)  Tax on Lump-Sum Distributions"
  echo "   5329)  Additional Taxes on Qualified Plans (inclucing IRAs) 
                  and Other Tax Favored Accounts"
  echo "   5405)  Repayment of First-Time Homebuyer Credit"
  echo "   5695)  Residential Energy Credits"
  echo "   6198)  At-Risk Limitations"
  echo "   6251)  Alternative Minimum Tax--Individuals"
  echo "   6252)  Installment Sale Income"
  echo "   7205)  Energy efficient commercial buildings deduction."
  echo "   8615)  Tax for Certain Children Who Have Unearned Income"
  echo "   8801)  Credit for Prior Year Minimum Tax--Individuals, Estates, and Trusts"
  echo "   8812)  Child Tax Credit"
  echo "   8814)  Parents' Election to Report Child's Interest and Dividends"
  echo "   8815)  "
  echo "   8829)  Expenses for Business Use of Your Home"
  echo "   8863)  Education Credits (American Opportunity and Lifetime Learning Credits)"
  echo "   8880)  Credit for Qualified Retirement Savings Contributions"
  echo "   8885)  Health Coverage Tax Credit"
  echo "   8888)  Allocation of Refund (Including Savings Bond Purchases)"
  echo "   8889)  Health Savings Accounts (HSAs)"  
  echo "   8903)  Domestic PRoduction Activities Deduction"
  echo "   8917)  Tuition and Fees Deduction"
  echo "   8919)  Uncollected Social Security and Medicare Taxes on Wages"
  echo
  echo "   8949a) Sales and Other Dispositons of Capital Assets,
                  basis reported on Form 1099-B."
  echo "   8949b) Sales and Other Dispositons of Capital Assets, 
                  basis not reported on Form 1099-B."
  echo "   8949c) Sales and Other Dispositons of Capital Assets, 
                  not on Form 1099-B."
  echo
  echo "   8959)  Additional Medicare Tax"
  echo "   8960)  Net Investment Income Tax--Individuals, Estates, and Trusts"
  echo "   8962)  Premium Tax Credit (PTC)"
  echo
  echo "   1099b)    Proceeds from Broker and Barter Exchange Transactions"
  echo "   1099div)  Dividends and Distributions"
  echo "   1099int)  Interest Income"
  echo "   1099msc)  Miscellaneous Income"
  echo "   1099r)    Distributions from Pensions, Annuities, Retirement etc."
  echo "   1099g)    Certain Government Payments"
  echo  
  echo "   w2)    Wage and Tax Statement"
  echo
  echo "   bkg) background"
  echo
  echo "   q)     Return to Main Menu"
  echo
  echo "Please enter the letter(s) of your choice then press return."
  read form_choice
  
    case $form_choice in

      1040)      set_menu_choices  f1040;;
      1040v)     set_menu_choices  1040v;;
      1116)      set_menu_choices  f1116;;
      2106)      set_menu_choices  f2106;;
      2439)      set_menu_choices  f2439;;
      2441)      set_menu_choices  f2441;;
      2555)      set_menu_choices  f2555;;
      3800)      set_menu_choices  f3800;;
      3903)      set_menu_choices  f3903;;
      4137)      set_menu_choices  f4137;;
      4562)      set_menu_choices  f4562;;
      4868)      set_menu_choices  f4868;;
      4797)      set_menu_choices  f4797;;
      4952)      set_menu_choices  f4952;;
      4972)      set_menu_choices  f4972;;
      5329)      set_menu_choices  f5329;;
      5405)      set_menu_choices  f5405;;
      5695)      set_menu_choices  f5695;;
      6198)      set_menu_choices  f6196;;
      6251)      set_menu_choices  f6251;;
      6252)      set_menu_choices  f6252;;
      7205)      set_menu_choices  f7205;;
      8615)      set_menu_choices  f8615;;
      8801)      set_menu_choices  f8801;;
      8812)      set_menu_choices  f8812;;
      8814)      set_menu_choices  f8814;;
      8815)      set_menu_choices  f8815;;
      8829)      set_menu_choices  f8829;;
      8863)      set_menu_choices  f8863;;
      8880)      set_menu_choices  f8880;;
      8885)      set_menu_choices  f8885;;
      8888)      set_menu_choices  f8888;;
      8889)      set_menu_choices  f8889;;
      8903)      set_menu_choices  f8903;;
      8917)      set_menu_choices  f8917;;
      8919)      set_menu_choices  f8919;;
      8949a)     set_menu_choices  f8949a;;
      8949b)     set_menu_choices  f8949b;;
      8949c)     set_menu_choices  f8949c;;
      8959)      set_menu_choices  f8959;;
      8960)      set_menu_choices  f8960;;
      8962)      set_menu_choices  f8962;;
      1099b)     set_menu_choices  f1099b;;
      1099div)   set_menu_choices  f1099div;;
      1099int)   set_menu_choices  1099int;;	
      1099msc)   set_menu_choices  f1099msc;;	
      1099r)     set_menu_choices  f1099r;;	
      1099g)     set_menu_choices  f1099g;;
      w2)        set_menu_choices  W2-CopyA;;	
#      bkg)       set_tableMenu_choices  bkg;; This choice removed since this one form is created from scratch. See  set_tableMenu_choices above.    
      q)         break;;
    esac
done

}

set_wkst_choice() {
while true;
do
  clear
  echo "Worksheets :"
  echo
  echo "    cap)   Capital Loss Carryover Worksheet"
  echo "    fei)   Foreign Earned Income Tax Worksheet"
  echo "    top)   Top of Foreign Earned Income Tax Worksheet"
  echo " bottom)   Bottom of Foreign Earned Income Tax Worksheet"  
  echo "   sltr)   State & Local Income Tax Refund Worksheet"
  echo "   qdcg)   Qualified Dividends & Capital Gain Tax Worksheet"
  echo "  qdcga)   Qualified Dividents & Capital Gain Tax WorksheetA"
  echo "   rg28)   28% Rate Gain"
  echo "   schd)   Schedule D worksheet"
  echo "  schda)   Schedule D worksheetA"
  echo "  sales)   State and Local Sales Tax Worksheet"
  echo "    sst)   Social Security Tax Worksheet"
  echo "   1250)   Unrecaptured Section 1250 Gains"
  
  
  echo "   q)      Return to Main Menu"
  echo
  echo "Please enter the letter(s) of your choice then press return."
  read wkst_choice

    case $wkst_choice in

       cap)   set_wksMenu_choices i1040sd;;
       fei)   set_wksMenu_choices i1040gi;;
       top)   set_wksMenu_choices i1040gi;;
    bottom)   set_wksMenu_choices i1040gi;;    
      sltr)   set_wksMenu_choices i1040gi;;
      qdcg)   set_wksMenu_choices i1040gi;;
     qdcga)   set_wksMenu_choices i1040gi;; 
      rg28)   set_wksMenu_choices i1040sd;;
      schd)   set_wksMenu_choices i1040sd;;
     schda)   set_wksMenu_choices i1040sd;; 
     sales)   set_wksMenu_choices i1040sca;;
       ssa)   set_wksMenu_choices i1040gi;;
       sst)   set_wksMenu_choices i1040gi;;
      1250)   set_wksMenu_choices i1040sd;;
         q)   break;;
    esac
done
 
}



set_menu_choice() {
while true;
  do     
  clear
  echo
  echo "Use this menu to choose the Form, Schedule, or Worksheet you wish to work on."
  echo
  echo "   f)  Show choice of Forms."
  echo "   s)  Show choice of Schedules."
  echo "   w)  Show choice of Worksheets."
  echo 
  echo "   q) Quit"
 
  echo "Please enter the number or letter(s) of your choice then press return."
  read menu_choice

    case "$menu_choice" in

      f)  set_form_choice;;	
      s)  set_schedule_choice;;
      w)  set_wkst_choice;;

      q)  exit;;
      *)  echo "Sorry, choice not recognized."
    esac
  done  
}

while true;
do
    set_menu_choice	
done
    
#Tidy up and leave

echo "Finished"

exit 0


