#! /bin/bash
f1=$1_Copy00.2fo
f2=$1_Copy02.2fo
#dir ../2Fo
cp ../2Fo/$f1 ../2Fo/$f2
sed 's/Copy00/Copy02/g' ../2Fo/$f2 > ../2Fo/$f2.tmp
sed 's/copy00/copy02/g' ../2Fo/$f2.tmp > ../2Fo/$f2
rm ../2Fo/$f2.tmp
#./pretty.sh $f2
