#! /bin/bash

#Copyright(C) 2023, 2024 Phillips Wedemeyer
#
#This file is part of a program called Tax-bash.
#
#Tax-bash is free software: you can redistibute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#Tax-bash is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with Tax-bash.  If not, see <https://www.gnu.org/licenses/>.
#
#


f1=$1_Copy00.2fo
f2=$1_Copy18.2fo
#dir ../2Fo
cp ../2Fo/$f1 ../2Fo/$f2
sed 's/Copy00/Copy18/g' ../2Fo/$f2 > ../2Fo/$f2.tmp
sed 's/copy00/copy18/g' ../2Fo/$f2.tmp > ../2Fo/$f2
rm ../2Fo/$f2.tmp
#./pretty.sh $f2
