#! /bin/bash
f1=v$1_Copy00.xsl
f2=v$1_Copy15.xsl
#dir ../Xsl
cp ../Variables/$f1 ../MyVariables/$f2
sed 's/Copy00/Copy15/g' ../MyVariables/$f2 > ../MyVariables/$f2.tmp
sed 's/copy00/copy15/g' ../MyVariables/$f2.tmp > ../MyVariables/$f2
rm ../MyVariables/$f2.tmp

f1=l$1_Copy00.xml
f2=l$1_Copy15.xml
#dir ../Xsl
cp ../Lines/$f1 ../MyLines/$f2
sed 's/Copy00/Copy15/g' ../MyLines/$f2 > ../MyLines/$f2.tmp
sed 's/copy00/copy15/g' ../MyLines/$f2.tmp > ../MyLines/$f2
rm ../MyLines/$f2.tmp

#This line combines the variable and lines to create ../Xsl/taxlogic.xsl
../BaseXsl/maketaxlogicXsl.sh



#./pretty.sh $f2
