#! /bin/bash

#Copyright(C) 2023, 2024 Phillips Wedemeyer
#
#This file is part of a program called Tax-bash.
#
#Tax-bash is free software: you can redistibute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#Tax-bash is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with Tax-bash.  If not, see <https://www.gnu.org/licenses/>.
#
#


f1=v$1_Copy00.xsl
f2=v$1_Copy05.xsl
#dir ../Xsl
cp ../Variables/$f1 ../MyVariables/$f2
sed 's/Copy00/Copy05/g' ../MyVariables/$f2 > ../MyVariables/$f2.tmp
sed 's/copy00/copy05/g' ../MyVariables/$f2.tmp > ../MyVariables/$f2
rm ../MyVariables/$f2.tmp

f1=l$1_Copy00.xml
f2=l$1_Copy05.xml
#dir ../Xsl
cp ../Lines/$f1 ../MyLines/$f2
sed 's/Copy00/Copy05/g' ../MyLines/$f2 > ../MyLines/$f2.tmp
sed 's/copy00/copy05/g' ../MyLines/$f2.tmp > ../MyLines/$f2
rm ../MyLines/$f2.tmp

#This line combines the variable and lines to create ../Xsl/taxlogic.xsl
../BaseXsl/maketaxlogicXsl.sh



#./pretty.sh $f2
